ALTER TABLE stores
ADD COLUMN IF NOT EXISTS accepts_pix BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS accepts_card BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS accepts_cash BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS pix_key TEXT,
ADD COLUMN IF NOT EXISTS pix_receipt_phone TEXT;
